### ISSUE TITLE
Does this support graphite reporting? If so can you provide an example?

### ISSUE THREAD

**Issue by mayooran99** [felixge/node-measured#21]
I need to create graphs and monitor the behavior like in the java metrics library. Does this support graphite reporting? If so, can you provide an example?

**Comment by mantoni** [comment]
I think that @felixge used this with graphite. I use it with elasticsearch (via [measured-elasticsearch](https://github.com/mantoni/measured-elasticsearch.js)). Therefore I don't have an example.

**Comment by mayooran99** [comment]
@felixge can you help with a graphite example?
