### ISSUE TITLE
Is it possible to enable and disable the metrics through configurations?

### ISSUE THREAD

**Issue by mayooran99** [felixge/node-measured#22]
Is it possible to turn off the metrics when its not required? Can we enable and disable it using some configuration file like in C# Metrics.NET project? If so, can you provide an example?

**Comment by mantoni** [comment]
I think turning metrics on or off is outside of the scope of this library. For this to work in a higher level library, the only thing missing is an `unregister` implementation as the counter-implementation to [register](https://github.com/felixge/node-measured/blob/master/lib/Collection.js#L10). If want to build something and need this addition, I'm happy to merge your pull request and release a new version.
